# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawurl',
            name='url',
            field=models.CharField(max_length=500, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
